from .io import read_signal_file, guess_numeric_views, write_wav, read_wav, read_audio_file, Ingestor, SignalBuffer
from .framing import FrameConfig, frame_signal, normalize_signal, detrend_mean, standardize_signal
from .features import frame_feature_vector, first_derivative, second_derivative
from .spectral import (
    dft,
    dominant_bins,
    spectral_energy,
    spectral_flatness,
    frequency_axis,
    power_spectrum,
    spectral_centroid,
    spectral_bandwidth,
    spectral_rolloff,
    band_energy,
    stft,
    spectrogram_matrix,
    autocorrelation,
    estimate_pitch,
)
from .detect import threshold_events, adaptive_threshold, adaptive_events, local_peaks, anomaly_score, onset_strength
from .bridge import (
    signal_signature,
    SignalSignature,
    signature_to_glyph_vector,
    LayeredSignalAnalysis,
    analyze_signal_layered,
    reconstruct_signal_from_signature,
)
from .bitlayer import analyze_bitlayer, build_bit_signature, BitSignature
from .modulate import amplitude_modulation, frequency_modulation
from .filters import moving_average, median_filter, remove_dc, normalize_peak, fft_bandpass
from .fingerprint import SignalFingerprint, fingerprint_engine, cosine_similarity, euclidean_distance, compare_fingerprints
from .pipeline import AdvancedSignalAnalysis, analyze_signal_advanced
from .filter_design import (
    FIRCoefficients,
    IIRCoefficients,
    AdaptiveFilterResult,
    apply_fir,
    apply_iir,
    fir_lowpass,
    fir_highpass,
    fir_bandpass,
    fir_bandstop,
    fractional_delay_fir,
    differentiator_fir,
    iir_integrator_leaky,
    iir_lowpass_single_pole,
    iir_highpass_single_pole,
    biquad_lowpass,
    biquad_highpass,
    biquad_bandpass,
    biquad_notch,
    biquad_allpass,
    comb_filter_feedforward,
    comb_filter_feedback,
    savitzky_golay_coefficients,
    savitzky_golay_filter,
    hilbert_transform_fft,
    analytic_signal,
    envelope,
    lms_adaptive_filter,
)
from .logging_utils import configure_logging, get_logger
from .complex_multichannel import (
    ComplexChannelResult,
    analytic_signal_multichannel,
    complex_channel_mix,
)
from .complex_spectral import (
    ComplexSpectralResult,
    complex_dft_multichannel,
    complex_spectral_mask,
    complex_spectral_shift,
)
from .complex_frame import (
    ComplexFrameResult,
    complex_stft_multichannel,
    complex_frame_operator,
)
from .complex_learnable_tf import (
    ComplexLearnableTFResult,
    complex_learnable_tf_operator,
    complex_learnable_tf_stack,
)
from .complex_multihead_tf import (
    ComplexMultiHeadTFResult,
    multihead_band_complex_tf_operator,
    multihead_band_complex_tf_stack,
)
from .complex_attention_tf import (
    ComplexCoupledAttentionTFResult,
    complex_multiband_head_coupling_operator,
    complex_multiband_head_coupling_stack,
    temporal_complex_head_coupling_operator,
    content_conditioned_temporal_head_coupling_operator,
    mode_conditioned_temporal_head_coupling_operator,
    long_memory_temporal_head_coupling_operator,
    stability_regularized_temporal_head_coupling_operator,
    joint_temporal_spectral_regularized_coupling_operator,
)
from .exceptions import SignalToolsError, SignalValidationError
from .forensics import (
    AuditStep,
    ChainOfCustody,
    ChainOfCustodyEvent,
    EvidenceHashes,
    EvidenceManifest,
    ForensicAnalysisResult,
    ForensicBundlePaths,
    ForensicProfile,
    FORENSIC_PROFILES,
    ReportSignature,
    TimestampSeal,
    append_chain_of_custody_event,
    create_chain_of_custody,
    create_evidence_manifest,
    create_timestamp_seal,
    forensic_analyze_signal,
    get_forensic_profile,
    hash_bytes,
    hash_file,
    sign_report,
    write_forensic_bundle,
)
from .graph_deep_filters import (
    GNNStackResult,
    MultiHeadAttentionResult,
    MultiHeadNodeAttentionResult,
    DeepGNNResult,
    GraphTransformerResult,
    EdgeConditionedConvResult,
    MessagePassingResult,
    QKVAttentionResult,
    ChannelMixResult,
    HybridTemporalAttentionResult,
    RecurrentHybridAttentionResult,
    HybridGatedMemoryResult,
    BidirectionalGatedMemoryResult,
    HierarchicalGatedMemoryResult,
    MultiscaleHierarchicalGatedMemoryResult,
    AttentiveMultiscaleHierarchicalGatedMemoryResult,
    graph_block_normalize,
    channel_mix,
    graph_block_normalize_multichannel,
    edge_aware_message_passing,
    edge_conditioned_convolution,
    edge_conditioned_conv_stack,
    edge_feature_message_passing_stack,
    graph_pool,
    graph_attention_matrix,
    graph_attention_filter,
    multihead_graph_attention,
    multihead_graph_attention_multichannel,
    qkv_graph_attention,
    masked_qkv_graph_attention,
    structured_edge_embedding_attention,
    spectral_gnn_filter,
    spectral_gnn_filter_multichannel,
    graph_scattering_transform,
    stacked_gnn,
    deep_gnn_stack,
    graph_transformer_layer,
    graph_transformer_stack,
    graph_transformer_qkv_layer,
    graph_transformer_qkv_stack,
    graph_transformer_masked_qkv_layer,
    graph_transformer_masked_qkv_stack,
    graph_transformer_enhanced_layer,
    graph_transformer_enhanced_stack,
    graph_transformer_edge_embedding_layer,
    graph_transformer_edge_embedding_stack,
    hybrid_node_edge_temporal_attention,
    hybrid_graph_temporal_transformer_layer,
    hybrid_graph_temporal_transformer_stack,
    recurrent_hybrid_node_edge_temporal_attention,
    recurrent_hybrid_graph_temporal_transformer_stack,
    hybrid_graph_temporal_gated_memory,
    hybrid_graph_temporal_gated_stack,
    bidirectional_hybrid_graph_temporal_gated_memory,
    bidirectional_hybrid_graph_temporal_gated_stack,
    hierarchical_hybrid_graph_temporal_gated_memory,
    hierarchical_hybrid_graph_temporal_gated_stack,
    multiscale_hierarchical_hybrid_graph_temporal_gated_memory,
    multiscale_hierarchical_hybrid_graph_temporal_gated_stack,
    attentive_multiscale_hierarchical_hybrid_graph_temporal_gated_memory,
    attentive_multiscale_hierarchical_hybrid_graph_temporal_gated_stack,
)
from .wavelet_packet import (
    WaveletPacketTree,
    available_wavelet_families,
    wavelet_family_kind,
    wavelet_filters,
    wavelet_packet_decompose,
    wavelet_packet_reconstruct,
)
from .wavelet_packet_2d import (
    WaveletPacket2DTree,
    wavelet_packet_2d_decompose,
    wavelet_packet_2d_reconstruct,
)
from .wavelet_packet_3d import (
    WaveletPacket3DTree,
    AnisotropicWaveletPacket3DTree,
    wavelet_packet_3d_decompose,
    wavelet_packet_3d_reconstruct,
    anisotropic_wavelet_packet_3d_decompose,
    anisotropic_wavelet_packet_3d_reconstruct,
)
from .wavelet_packet_4d import (
    WaveletPacket4DTree,
    AnisotropicWaveletPacket4DTree,
    wavelet_packet_4d_decompose,
    wavelet_packet_4d_reconstruct,
    anisotropic_wavelet_packet_4d_decompose,
    anisotropic_wavelet_packet_4d_reconstruct,
)
from .wavelet_packet_5d import (
    WaveletPacket5DTree,
    AnisotropicWaveletPacket5DTree,
    AdaptiveWaveletPacket5DTree,
    BlockAdaptiveWaveletPacket5DTree,
    SpatiallyAdaptiveWaveletPacket5DTree,
    SubbandAdaptiveWaveletPacket5DTree,
    RegularizedAdaptiveWaveletPacket5DTree,
    SubbandAttentiveWaveletPacket5DTree,
    CrossBranchAttentiveWaveletPacket5DTree,
    WeightedMultiObjectiveWaveletPacket5DTree,
    LearnableWeightedMultiObjectiveWaveletPacket5DTree,
    LevelAttentiveWaveletPacket5DTree,
    wavelet_packet_5d_decompose,
    wavelet_packet_5d_reconstruct,
    anisotropic_wavelet_packet_5d_decompose,
    anisotropic_wavelet_packet_5d_reconstruct,
    select_wavelet_family_per_axis_5d,
    adaptive_wavelet_packet_5d_decompose,
    adaptive_wavelet_packet_5d_reconstruct,
    select_wavelet_family_per_axis_5d_local_blocks,
    adaptive_blockwise_wavelet_packet_5d_decompose,
    adaptive_blockwise_wavelet_packet_5d_reconstruct,
    spatially_variable_wavelet_packet_5d_decompose,
    spatially_variable_wavelet_packet_5d_reconstruct,
    subband_adaptive_wavelet_packet_5d_decompose,
    subband_adaptive_wavelet_packet_5d_reconstruct,
    regularized_select_wavelet_family_per_axis_5d,
    regularized_adaptive_wavelet_packet_5d_decompose,
    regularized_adaptive_wavelet_packet_5d_reconstruct,
    subband_attentive_wavelet_packet_5d_decompose,
    subband_attentive_wavelet_packet_5d_reconstruct,
    cross_branch_attentive_wavelet_packet_5d_decompose,
    cross_branch_attentive_wavelet_packet_5d_reconstruct,
    weighted_multiobjective_select_wavelet_family_per_axis_5d,
    weighted_multiobjective_wavelet_packet_5d_decompose,
    weighted_multiobjective_wavelet_packet_5d_reconstruct,
    learnable_multiobjective_weight_search_5d,
    learnable_multiobjective_wavelet_packet_5d_decompose,
    learnable_multiobjective_wavelet_packet_5d_reconstruct,
    level_attentive_wavelet_packet_5d_decompose,
    level_attentive_wavelet_packet_5d_reconstruct,
)
from .image_decomposition import (
    ImageLayerDecomposition,
    SavedLayerImages,
    WaveletSubbands2D,
    build_layer_alpha_masks,
    decompose_image_layers,
    decompose_shadows_specular,
    denoise_image,
    detect_reflections,
    estimate_background,
    estimate_illumination,
    estimate_noise,
    extract_foreground,
    extract_texture,
    mean_filter_2d,
    reconstruct_from_layers,
    rgb_to_gray,
    save_alpha_masks,
    save_decomposition_layers,
    save_layer_image,
    segment_ink_strokes,
    simple_edges,
    wavelet_subbands_2d,
)
from .image_visualization import (
    ComparisonMosaicResult,
    export_comparison_mosaic,
)
from .image_forensics import (
    ForensicImageAnalysisResult,
    ForensicImageBundlePaths,
    forensic_decompose_image,
)
from .image_morphology import (
    dilation_2d,
    erosion_2d,
    opening_2d,
    closing_2d,
    median_filter_2d,
    morphological_gradient_2d,
    dilation_3d,
    erosion_3d,
    opening_3d,
    closing_3d,
    median_filter_3d,
    morphological_gradient_3d,
    dilation_3d_kernel,
    erosion_3d_kernel,
    opening_3d_kernel,
    closing_3d_kernel,
)
from .advanced_state_filters import (
    AdaptiveWienerResult,
    NonlinearFilterResult,
    ParticleFilterResult,
    SmootherResult,
    adaptive_wiener_filter_1d,
    extended_kalman_filter,
    unscented_kalman_filter,
    particle_filter_1d,
    backward_exponential_smoother,
    rts_smoother,
    particle_filter_nonlinear,
    particle_filter_multivariate,
)
from .graph_wavelets import (
    chebyshev_graph_filter,
    graph_wavelet_kernel,
    graph_wavelet_transform,
)
from .graph_positional import (
    laplacian_positional_encoding,
    random_walk_positional_encoding,
    augment_with_graph_positional_encoding,
)
from .filter_banks import (
    FilterBankResult,
    haar_analysis_bank,
    haar_synthesis_bank,
    uniform_filter_bank,
    reconstruct_uniform_filter_bank,
)
from .image_decomposition import (
    ImageLayerDecomposition,
    SavedLayerImages,
    WaveletSubbands2D,
    build_layer_alpha_masks,
    decompose_image_layers,
    decompose_shadows_specular,
    denoise_image,
    detect_reflections,
    estimate_background,
    estimate_illumination,
    estimate_noise,
    extract_foreground,
    extract_texture,
    mean_filter_2d,
    reconstruct_from_layers,
    rgb_to_gray,
    save_alpha_masks,
    save_decomposition_layers,
    save_layer_image,
    segment_ink_strokes,
    simple_edges,
    wavelet_subbands_2d,
)
from .image_visualization import (
    ComparisonMosaicResult,
    export_comparison_mosaic,
)
from .image_forensics import (
    ForensicImageAnalysisResult,
    ForensicImageBundlePaths,
    forensic_decompose_image,
)
from .image_morphology import (
    dilation_2d,
    erosion_2d,
    opening_2d,
    closing_2d,
    median_filter_2d,
    morphological_gradient_2d,
)
from .advanced_state_filters import (
    AdaptiveWienerResult,
    NonlinearFilterResult,
    ParticleFilterResult,
    adaptive_wiener_filter_1d,
    extended_kalman_filter,
    unscented_kalman_filter,
    particle_filter_1d,
)
from .multirate import (
    polyphase_decompose,
    decimate,
    interpolate,
    two_band_analysis_bank,
)
from .graph_filters import (
    graph_laplacian,
    graph_fourier_basis,
    graph_filter_signal,
    graph_polynomial_filter,
)
from .morphology import (
    advanced_median_filter,
    rank_filter,
    dilation_1d,
    erosion_1d,
    opening_1d,
    closing_1d,
    morphological_gradient_1d,
)
from .state_filters import (
    KalmanFilterResult,
    WienerFilterResult,
    kalman_filter_1d,
    wiener_filter_1d,
)

__all__ = [
    "level_attentive_wavelet_packet_5d_reconstruct",
    "level_attentive_wavelet_packet_5d_decompose",
    "LevelAttentiveWaveletPacket5DTree",
    "learnable_multiobjective_wavelet_packet_5d_reconstruct",
    "learnable_multiobjective_wavelet_packet_5d_decompose",
    "learnable_multiobjective_weight_search_5d",
    "LearnableWeightedMultiObjectiveWaveletPacket5DTree",
    "joint_temporal_spectral_regularized_coupling_operator",
    "weighted_multiobjective_wavelet_packet_5d_reconstruct",
    "weighted_multiobjective_wavelet_packet_5d_decompose",
    "weighted_multiobjective_select_wavelet_family_per_axis_5d",
    "WeightedMultiObjectiveWaveletPacket5DTree",
    "cross_branch_attentive_wavelet_packet_5d_reconstruct",
    "cross_branch_attentive_wavelet_packet_5d_decompose",
    "CrossBranchAttentiveWaveletPacket5DTree",
    "stability_regularized_temporal_head_coupling_operator",
    "long_memory_temporal_head_coupling_operator",
    "SubbandAttentiveWaveletPacket5DTree",
    "subband_attentive_wavelet_packet_5d_reconstruct",
    "subband_attentive_wavelet_packet_5d_decompose",
    "RegularizedAdaptiveWaveletPacket5DTree",
    "regularized_adaptive_wavelet_packet_5d_reconstruct",
    "regularized_adaptive_wavelet_packet_5d_decompose",
    "regularized_select_wavelet_family_per_axis_5d",
    "mode_conditioned_temporal_head_coupling_operator",
    "subband_adaptive_wavelet_packet_5d_reconstruct",
    "subband_adaptive_wavelet_packet_5d_decompose",
    "SubbandAdaptiveWaveletPacket5DTree",
    "attentive_multiscale_hierarchical_hybrid_graph_temporal_gated_stack",
    "attentive_multiscale_hierarchical_hybrid_graph_temporal_gated_memory",
    "AttentiveMultiscaleHierarchicalGatedMemoryResult",
    "content_conditioned_temporal_head_coupling_operator",
    "spatially_variable_wavelet_packet_5d_reconstruct",
    "spatially_variable_wavelet_packet_5d_decompose",
    "SpatiallyAdaptiveWaveletPacket5DTree",
    "multiscale_hierarchical_hybrid_graph_temporal_gated_stack",
    "multiscale_hierarchical_hybrid_graph_temporal_gated_memory",
    "MultiscaleHierarchicalGatedMemoryResult",
    "temporal_complex_head_coupling_operator",
    "adaptive_blockwise_wavelet_packet_5d_reconstruct",
    "adaptive_blockwise_wavelet_packet_5d_decompose",
    "select_wavelet_family_per_axis_5d_local_blocks",
    "BlockAdaptiveWaveletPacket5DTree",
    "hierarchical_hybrid_graph_temporal_gated_stack",
    "hierarchical_hybrid_graph_temporal_gated_memory",
    "HierarchicalGatedMemoryResult",
    "complex_multiband_head_coupling_stack",
    "complex_multiband_head_coupling_operator",
    "ComplexCoupledAttentionTFResult",
    "adaptive_wavelet_packet_5d_reconstruct",
    "adaptive_wavelet_packet_5d_decompose",
    "select_wavelet_family_per_axis_5d",
    "AdaptiveWaveletPacket5DTree",
    "bidirectional_hybrid_graph_temporal_gated_stack",
    "bidirectional_hybrid_graph_temporal_gated_memory",
    "BidirectionalGatedMemoryResult",
    "multihead_band_complex_tf_stack",
    "multihead_band_complex_tf_operator",
    "ComplexMultiHeadTFResult",
    "hybrid_graph_temporal_gated_stack",
    "hybrid_graph_temporal_gated_memory",
    "HybridGatedMemoryResult",
    "complex_learnable_tf_stack",
    "complex_learnable_tf_operator",
    "ComplexLearnableTFResult",
    "anisotropic_wavelet_packet_5d_reconstruct",
    "anisotropic_wavelet_packet_5d_decompose",
    "wavelet_packet_5d_reconstruct",
    "wavelet_packet_5d_decompose",
    "AnisotropicWaveletPacket5DTree",
    "WaveletPacket5DTree",
    "recurrent_hybrid_graph_temporal_transformer_stack",
    "recurrent_hybrid_node_edge_temporal_attention",
    "RecurrentHybridAttentionResult",
    "complex_frame_operator",
    "complex_stft_multichannel",
    "ComplexFrameResult",
    "read_signal_file", "guess_numeric_views", "write_wav", "read_wav", "read_audio_file", "Ingestor", "SignalBuffer",
    "FrameConfig", "frame_signal", "normalize_signal", "detrend_mean", "standardize_signal",
    "frame_feature_vector", "first_derivative", "second_derivative",
    "dft", "dominant_bins", "spectral_energy", "spectral_flatness", "frequency_axis", "power_spectrum",
    "spectral_centroid", "spectral_bandwidth", "spectral_rolloff", "band_energy", "stft", "spectrogram_matrix",
    "autocorrelation", "estimate_pitch",
    "threshold_events", "adaptive_threshold", "adaptive_events", "local_peaks", "anomaly_score", "onset_strength",
    "signal_signature", "SignalSignature", "signature_to_glyph_vector", "LayeredSignalAnalysis",
    "analyze_signal_layered", "reconstruct_signal_from_signature",
    "analyze_bitlayer", "build_bit_signature", "BitSignature",
    "amplitude_modulation", "frequency_modulation",
    "moving_average", "median_filter", "remove_dc", "normalize_peak", "fft_bandpass",
    "FIRCoefficients", "IIRCoefficients", "AdaptiveFilterResult",
    "apply_fir", "apply_iir",
    "fir_lowpass", "fir_highpass", "fir_bandpass", "fir_bandstop",
    "fractional_delay_fir", "differentiator_fir",
    "iir_integrator_leaky", "iir_lowpass_single_pole", "iir_highpass_single_pole",
    "biquad_lowpass", "biquad_highpass", "biquad_bandpass", "biquad_notch", "biquad_allpass",
    "comb_filter_feedforward", "comb_filter_feedback",
    "savitzky_golay_coefficients", "savitzky_golay_filter",
    "hilbert_transform_fft", "analytic_signal", "envelope", "lms_adaptive_filter",
    "SignalFingerprint", "fingerprint_engine", "cosine_similarity", "euclidean_distance", "compare_fingerprints",
    "AdvancedSignalAnalysis", "analyze_signal_advanced",
    "configure_logging", "get_logger",
    "ComplexChannelResult", "analytic_signal_multichannel", "complex_channel_mix",
    "ComplexSpectralResult", "complex_dft_multichannel", "complex_spectral_mask", "complex_spectral_shift",
        "KalmanFilterResult", "WienerFilterResult", "kalman_filter_1d", "wiener_filter_1d",
    "advanced_median_filter", "rank_filter", "dilation_1d", "erosion_1d", "opening_1d", "closing_1d", "morphological_gradient_1d",
    "graph_laplacian", "graph_fourier_basis", "graph_filter_signal", "graph_polynomial_filter",
    "polyphase_decompose", "decimate", "interpolate", "two_band_analysis_bank",
    "AdaptiveWienerResult", "NonlinearFilterResult", "ParticleFilterResult", "SmootherResult",
    "adaptive_wiener_filter_1d", "extended_kalman_filter", "unscented_kalman_filter", "particle_filter_1d",
    "backward_exponential_smoother", "rts_smoother", "particle_filter_nonlinear", "particle_filter_multivariate",
    "dilation_2d", "erosion_2d", "opening_2d", "closing_2d", "median_filter_2d", "morphological_gradient_2d",
    "dilation_3d", "erosion_3d", "opening_3d", "closing_3d", "median_filter_3d", "morphological_gradient_3d",
    "dilation_3d_kernel", "erosion_3d_kernel", "opening_3d_kernel", "closing_3d_kernel",
    "FilterBankResult", "haar_analysis_bank", "haar_synthesis_bank", "uniform_filter_bank", "reconstruct_uniform_filter_bank",
    "WaveletPacketTree", "available_wavelet_families", "wavelet_family_kind", "wavelet_filters", "wavelet_packet_decompose", "wavelet_packet_reconstruct",
    "WaveletPacket2DTree", "wavelet_packet_2d_decompose", "wavelet_packet_2d_reconstruct",
    "WaveletPacket3DTree", "AnisotropicWaveletPacket3DTree", "wavelet_packet_3d_decompose", "wavelet_packet_3d_reconstruct", "anisotropic_wavelet_packet_3d_decompose", "anisotropic_wavelet_packet_3d_reconstruct",
    "WaveletPacket4DTree", "AnisotropicWaveletPacket4DTree", "wavelet_packet_4d_decompose", "wavelet_packet_4d_reconstruct", "anisotropic_wavelet_packet_4d_decompose", "anisotropic_wavelet_packet_4d_reconstruct",
    "chebyshev_graph_filter", "graph_wavelet_kernel", "graph_wavelet_transform",
    "laplacian_positional_encoding", "random_walk_positional_encoding", "augment_with_graph_positional_encoding",
    "GNNStackResult", "MultiHeadAttentionResult", "MultiHeadNodeAttentionResult", "DeepGNNResult", "GraphTransformerResult", "EdgeConditionedConvResult", "MessagePassingResult", "QKVAttentionResult", "ChannelMixResult", "HybridTemporalAttentionResult", "graph_block_normalize", "channel_mix", "graph_block_normalize_multichannel", "edge_aware_message_passing", "edge_conditioned_convolution", "edge_conditioned_conv_stack", "edge_feature_message_passing_stack", "graph_pool", "graph_attention_matrix", "graph_attention_filter", "multihead_graph_attention", "multihead_graph_attention_multichannel", "qkv_graph_attention", "masked_qkv_graph_attention", "structured_edge_embedding_attention", "spectral_gnn_filter", "spectral_gnn_filter_multichannel", "graph_scattering_transform", "stacked_gnn", "deep_gnn_stack", "graph_transformer_layer", "graph_transformer_stack", "graph_transformer_qkv_layer", "graph_transformer_qkv_stack", "graph_transformer_masked_qkv_layer", "graph_transformer_masked_qkv_stack", "graph_transformer_enhanced_layer", "graph_transformer_enhanced_stack", "graph_transformer_edge_embedding_layer", "graph_transformer_edge_embedding_stack", "hybrid_node_edge_temporal_attention", "hybrid_graph_temporal_transformer_layer", "hybrid_graph_temporal_transformer_stack",
    "SignalToolsError", "SignalValidationError",
]
